### ISSUE TITLE
error thrown when running a pysnobal run after running awsm normally

### ISSUE THREAD

**Issue by micahjohnson150** [USDA-ARS-NWRC/awsm#27]
I got the error when running out test_data configs back to back. After running the pysnobal config, I attempted to run the config.ini and this error was produced. It sounds like this is due to the fact the netcdfs are still around and messes up the wyhr conversion of the ipw files. It would be nice if we sorted through this automatically.

```
Traceback (most recent call last):
  File "/home/micahjohnson/projects/venv/smrf35/bin/awsm", line 4, in <module>
    __import__('pkg_resources').run_script('awsm==0.4.0', 'awsm')
  File "/home/micahjohnson/projects/venv/smrf35/lib/python3.5/site-packages/pkg_resources/__init__.py", line 658, in run_script
    self.require(requires)[0].run_script(script_name, ns)
  File "/home/micahjohnson/projects/venv/smrf35/lib/python3.5/site-packages/pkg_resources/__init__.py", line 1438, in run_script
    exec(code, namespace, namespace)
  File "/home/micahjohnson/projects/venv/smrf35/lib/python3.5/site-packages/awsm-0.4.0-py3.5.egg/EGG-INFO/scripts/awsm", line 74, in <module>
    run()
  File "/home/micahjohnson/projects/venv/smrf35/lib/python3.5/site-packages/awsm-0.4.0-py3.5.egg/EGG-INFO/scripts/awsm", line 49, in run
    a.ipw2nc(runtype)
  File "/home/micahjohnson/projects/venv/smrf35/lib/python3.5/site-packages/awsm-0.4.0-py3.5.egg/awsm/framework/framework.py", line 375, in ipw2nc
    cvf.ipw2nc_mea(self, runtype)
  File "/home/micahjohnson/projects/venv/smrf35/lib/python3.5/site-packages/awsm-0.4.0-py3.5.egg/awsm/convertFiles/convertFiles.py", line 319, in ipw2nc_mea
    hr = int(nm.split('.')[1])
ValueError: invalid literal for int() with base 10: 'nc'
```

**Comment by micah-prime** [comment]
Fixed in develop
